import os
import sys
import csv
from xml.etree import ElementTree as ET
from pathlib import Path

def create_scale_setup(subject_id, mass, height, subj_dir, model_file):
    """Create a scale setup XML file for a subject."""
    
    # Template XML structure
    xml_template = """<?xml version="1.0" encoding="UTF-8" ?>
<OpenSimDocument Version="40500">
    <ScaleTool name="{subject_id}">
        <!--Mass of the subject in kg.  Subject-specific model generated by scaling step will have this total mass.-->
        <mass>{mass}</mass>
        <!--Height of the subject in mm.  For informational purposes only (not used by scaling).-->
        <height>{height}</height>
        <!--Age of the subject in years.  For informational purposes only (not used by scaling).-->
        <age>0</age>
        <!--Notes for the subject.-->
        <notes>Auto-generated scale setup for {subject_id}</notes>
        <!--Specifies the name of the unscaled model (.osim) and the marker set.-->
        <GenericModelMaker>
            <!--Model file (.osim) for the unscaled model.-->
            <model_file>{model_file}</model_file>
            <!--Set of model markers used to scale the model. Scaling is done based on distances between model markers compared to the same distances between the corresponding experimental markers.-->
            <marker_set_file>Unassigned</marker_set_file>
        </GenericModelMaker>
        <!--Specifies parameters for scaling the model.-->
        <ModelScaler>
            <!--Whether or not to use the model scaler during scale-->
            <apply>true</apply>
            <!--Specifies the scaling method and order. Valid options are 'measurements', 'manualScale', singly or both in any sequence.-->
            <scaling_order> measurements</scaling_order>
            <!--Specifies the measurements by which body segments are to be scaled.-->
            <MeasurementSet name="RajagopalLa2023_LL-stw_adjustedWieghts">
                <objects>
                    <Measurement name="pelvis">
                        <!--Flag to turn on and off scaling for this measurement.-->
                        <apply>true</apply>
                        <!--Set of marker pairs used to determine the scale factors.-->
                        <MarkerPairSet>
                            <objects>
                                <MarkerPair>
                                    <!--Names of two markers, the distance between which is used to compute a body scale factor.-->
                                    <markers> RASIS LASIS</markers>
                                </MarkerPair>
                            </objects>
                            <groups />
                        </MarkerPairSet>
                        <!--Set of bodies to be scaled by this measurement.-->
                        <BodyScaleSet>
                            <objects>
                                <BodyScale name="pelvis">
                                    <!--Axes (X Y Z) along which to scale a body. For example, 'X Y Z' scales along all three axes, and 'Y' scales just along the Y axis.-->
                                    <axes> X Y Z</axes>
                                </BodyScale>
                            </objects>
                            <groups />
                        </BodyScaleSet>
                    </Measurement>
                    <Measurement name="thigh">
                        <!--Flag to turn on and off scaling for this measurement.-->
                        <apply>true</apply>
                        <!--Set of marker pairs used to determine the scale factors.-->
                        <MarkerPairSet>
                            <objects>
                                <MarkerPair>
                                    <!--Names of two markers, the distance between which is used to compute a body scale factor.-->
                                    <markers> RASIS RFLE</markers>
                                </MarkerPair>
                                <MarkerPair>
                                    <!--Names of two markers, the distance between which is used to compute a body scale factor.-->
                                    <markers> LASIS LFLE</markers>
                                </MarkerPair>
                            </objects>
                            <groups />
                        </MarkerPairSet>
                        <!--Set of bodies to be scaled by this measurement.-->
                        <BodyScaleSet>
                            <objects>
                                <BodyScale name="femur_r">
                                    <!--Axes (X Y Z) along which to scale a body. For example, 'X Y Z' scales along all three axes, and 'Y' scales just along the Y axis.-->
                                    <axes> X Y Z</axes>
                                </BodyScale>
                                <BodyScale name="patella_r">
                                    <!--Axes (X Y Z) along which to scale a body. For example, 'X Y Z' scales along all three axes, and 'Y' scales just along the Y axis.-->
                                    <axes> X Y Z</axes>
                                </BodyScale>
                                <BodyScale name="femur_l">
                                    <!--Axes (X Y Z) along which to scale a body. For example, 'X Y Z' scales along all three axes, and 'Y' scales just along the Y axis.-->
                                    <axes> X Y Z</axes>
                                </BodyScale>
                                <BodyScale name="patella_l">
                                    <!--Axes (X Y Z) along which to scale a body. For example, 'X Y Z' scales along all three axes, and 'Y' scales just along the Y axis.-->
                                    <axes> X Y Z</axes>
                                </BodyScale>
                            </objects>
                            <groups />
                        </BodyScaleSet>
                    </Measurement>
                    <Measurement name="shank">
                        <!--Flag to turn on and off scaling for this measurement.-->
                        <apply>true</apply>
                        <!--Set of marker pairs used to determine the scale factors.-->
                        <MarkerPairSet>
                            <objects>
                                <MarkerPair>
                                    <!--Names of two markers, the distance between which is used to compute a body scale factor.-->
                                    <markers> RFLE RFAL</markers>
                                </MarkerPair>
                                <MarkerPair>
                                    <!--Names of two markers, the distance between which is used to compute a body scale factor.-->
                                    <markers> LFLE LFAL</markers>
                                </MarkerPair>
                            </objects>
                            <groups />
                        </MarkerPairSet>
                        <!--Set of bodies to be scaled by this measurement.-->
                        <BodyScaleSet>
                            <objects>
                                <BodyScale name="tibia_r">
                                    <!--Axes (X Y Z) along which to scale a body. For example, 'X Y Z' scales along all three axes, and 'Y' scales just along the Y axis.-->
                                    <axes> X Y Z</axes>
                                </BodyScale>
                                <BodyScale name="talus_r">
                                    <!--Axes (X Y Z) along which to scale a body. For example, 'X Y Z' scales along all three axes, and 'Y' scales just along the Y axis.-->
                                    <axes> X Y Z</axes>
                                </BodyScale>
                                <BodyScale name="tibia_l">
                                    <!--Axes (X Y Z) along which to scale a body. For example, 'X Y Z' scales along all three axes, and 'Y' scales just along the Y axis.-->
                                    <axes> X Y Z</axes>
                                </BodyScale>
                                <BodyScale name="talus_l">
                                    <!--Axes (X Y Z) along which to scale a body. For example, 'X Y Z' scales along all three axes, and 'Y' scales just along the Y axis.-->
                                    <axes> X Y Z</axes>
                                </BodyScale>
                            </objects>
                            <groups />
                        </BodyScaleSet>
                    </Measurement>
                    <Measurement name="foot">
                        <!--Flag to turn on and off scaling for this measurement.-->
                        <apply>true</apply>
                        <!--Set of marker pairs used to determine the scale factors.-->
                        <MarkerPairSet>
                            <objects>
                                <MarkerPair>
                                    <!--Names of two markers, the distance between which is used to compute a body scale factor.-->
                                    <markers> RFCC RFMT2</markers>
                                </MarkerPair>
                                <MarkerPair>
                                    <!--Names of two markers, the distance between which is used to compute a body scale factor.-->
                                    <markers> LFCC LFMT2</markers>
                                </MarkerPair>
                            </objects>
                            <groups />
                        </MarkerPairSet>
                        <!--Set of bodies to be scaled by this measurement.-->
                        <BodyScaleSet>
                            <objects>
                                <BodyScale name="calcn_r">
                                    <!--Axes (X Y Z) along which to scale a body. For example, 'X Y Z' scales along all three axes, and 'Y' scales just along the Y axis.-->
                                    <axes> X Y Z</axes>
                                </BodyScale>
                                <BodyScale name="toes_r">
                                    <!--Axes (X Y Z) along which to scale a body. For example, 'X Y Z' scales along all three axes, and 'Y' scales just along the Y axis.-->
                                    <axes> X Y Z</axes>
                                </BodyScale>
                                <BodyScale name="calcn_l">
                                    <!--Axes (X Y Z) along which to scale a body. For example, 'X Y Z' scales along all three axes, and 'Y' scales just along the Y axis.-->
                                    <axes> X Y Z</axes>
                                </BodyScale>
                                <BodyScale name="toes_l">
                                    <!--Axes (X Y Z) along which to scale a body. For example, 'X Y Z' scales along all three axes, and 'Y' scales just along the Y axis.-->
                                    <axes> X Y Z</axes>
                                </BodyScale>
                            </objects>
                            <groups />
                        </BodyScaleSet>
                    </Measurement>
                </objects>
                <groups />
            </MeasurementSet>
            <!--TRC file (.trc) containing the marker positions used for measurement-based scaling. This is usually a static trial, but doesn't need to be.  The marker-pair distances are computed for each time step in the TRC file and averaged across the time range.-->
            <marker_file>-1</marker_file>
            <!--Time range over which to average marker-pair distances in the marker file (.trc) for measurement-based scaling.-->
            <time_range> 1 2.9500000000000001776</time_range>
            <!--Flag (true or false) indicating whether or not to preserve relative mass between segments.-->
            <preserve_mass_distribution>true</preserve_mass_distribution>
            <!--Name of OpenSim model file (.osim) to write when done scaling.-->
            <output_model_file>{subject_id}_scaledOnly.osim</output_model_file>
            <!--Name of file to write containing the scale factors that were applied to the unscaled model (optional).-->
            <output_scale_file>{subject_id}_scaleSet_applied.xml</output_scale_file>
        </ModelScaler>
        <!--Specifies parameters for placing markers on the model once a model is scaled. -->
        <MarkerPlacer>
            <!--Whether or not to use the marker placer during scale-->
            <apply>true</apply>
            <!--Task set used to specify weights used in the IK computation of the static pose.-->
            <IKTaskSet name="gait2392_Scale">
                <objects />
                <groups />
            </IKTaskSet>
            <!--TRC file (.trc) containing the time history of experimental marker positions (usually a static trial).-->
            <marker_file>-1</marker_file>
            <!--Time range over which the marker positions are averaged.-->
            <time_range> 1 2.9500000000000001776</time_range>
            <!--Name of the motion file (.mot) written after marker relocation (optional).-->
            <output_motion_file>{subject_id}_static_output.mot</output_motion_file>
            <!--Output OpenSim model file (.osim) after scaling and maker placement.-->
            <output_model_file>{subject_id}_simbody_scaled.osim</output_model_file>
            <!--Output marker set containing the new marker locations after markers have been placed.-->
            <output_marker_file>{subject_id}_marker_scaled.xml</output_marker_file>
            <!--Maximum amount of movement allowed in marker data when averaging frames of the static trial. A negative value means there is not limit.-->
            <max_marker_movement>-1</max_marker_movement>
        </MarkerPlacer>
    </ScaleTool>
</OpenSimDocument>"""
    
    # Format the XML with subject data
    xml_content = xml_template.format(
        subject_id=subject_id,
        mass=mass,
        height=height,
        model_file=model_file
    )
    
    # Write to file
    output_file = Path(os.path.join(subj_dir,"scale", f"scale_{subject_id}_setup.xml"))
    os.makedirs(output_file.parent, exist_ok=True)
    
    with open(output_file, 'w') as f:
        f.write(xml_content)
    
    print(f"Created: {output_file}")

def main():
    if len(sys.argv) < 4:
        print("Usage: python scale_setup.py <subject_num>, <subj_dir>, <model_file>")
        sys.exit(1)
    os.chdir(Path(__file__).parent)  # Change to the directory of the script to ensure relative paths work
    csv_file = '../Subject Details.csv'  # CSV file with subject_id, mass, height
    subj_dir = Path(sys.argv[2])
    model_file = Path(sys.argv[3])
    print("*"*500)

    
    # Read CSV file
    try:
        with open(csv_file, 'r') as f:
            reader = csv.DictReader(f)
            print(reader.fieldnames)
            for row in reader:
                if row['Subject Number'] == Path(subj_dir).name:
                    subject_id = row['Subject Number']
                    mass = row['Weight (kg)']
                    height = row['Height (m)']
                    
                    # subj_dir = os.path.join(subj_dir, subject_id)
                    create_scale_setup(subject_id, mass, height, subj_dir, model_file)
        # for row in reader:
        #     subject_id = row['subject_id']
        #     mass = row['mass']
        #     height = row['height']
            
        #     subj_dir = os.path.join(subj_dir, subject_id)
        #     create_scale_setup(subject_id, mass, height, subj_dir)
    except FileNotFoundError:
        print(f"Error: CSV file '{csv_file}' not found")
        sys.exit(1)
    # except KeyError as e:
    #     print(f"Error: Missing required column {e} in CSV file")
    #     sys.exit(1)

if __name__ == "__main__":
    main()